# Generated by Django 3.1.3 on 2020-12-04 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CityVenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='season.city')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('toss_decision', models.IntegerField(choices=[(1, 'Bat'), (2, 'Field'), (0, 'Bad Data')], default=0)),
                ('result', models.IntegerField(choices=[(1, 'Normal'), (2, 'Tie'), (0, 'No Result')], default=1)),
                ('dl_applied', models.IntegerField(default=0)),
                ('won_by', models.IntegerField(choices=[(1, 'Runs'), (2, 'Wickets'), (0, 'Unknown')], default=1)),
                ('score', models.IntegerField(default=0)),
                ('csv_match_id', models.IntegerField()),
                ('man_of_match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='season.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='season.season')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Umpire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonTeamPlay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inning', models.IntegerField()),
                ('over', models.IntegerField()),
                ('ball', models.IntegerField()),
                ('is_super_over', models.BooleanField(default=False)),
                ('wide_runs', models.IntegerField(default=0)),
                ('bye_runs', models.IntegerField(default=0)),
                ('leg_bye_runs', models.IntegerField(default=0)),
                ('no_ball_runs', models.IntegerField(default=0)),
                ('penalty_runs', models.IntegerField(default=0)),
                ('batsman_runs', models.IntegerField(default=0)),
                ('extra_runs', models.IntegerField(default=0)),
                ('dismissal_kind', models.IntegerField(choices=[(0, 'Not Out'), (1, 'Bowled'), (2, 'Caught'), (3, 'Caught and Bowled'), (4, 'Leg Bowled Wicket'), (5, 'Run Out'), (6, 'Stumped'), (7, 'Hit Wicket'), (8, 'Obstructing The Field'), (9, 'Retired Hurt')], default=0)),
                ('batsman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_batsman', to='season.player')),
                ('batting_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batting_team', to='season.team')),
                ('bowler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_bowler', to='season.player')),
                ('bowling_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bowling_team', to='season.team')),
                ('dismissed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_dismissed', to='season.player')),
                ('fielder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_fielder', to='season.player')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='season.seasonmatch')),
                ('non_striker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_non_striker', to='season.player')),
            ],
        ),
        migrations.AddField(
            model_name='seasonmatch',
            name='team_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_team1', to='season.team'),
        ),
        migrations.AddField(
            model_name='seasonmatch',
            name='team_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_team2', to='season.team'),
        ),
        migrations.AddField(
            model_name='seasonmatch',
            name='toss_won_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_toss_won', to='season.team'),
        ),
        migrations.AddField(
            model_name='seasonmatch',
            name='umpire_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_umpire', to='season.umpire'),
        ),
        migrations.AddField(
            model_name='seasonmatch',
            name='umpire_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_umpire', to='season.umpire'),
        ),
        migrations.AddField(
            model_name='seasonmatch',
            name='umpire_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_umpire', to='season.umpire'),
        ),
        migrations.AddField(
            model_name='seasonmatch',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_location', to='season.cityvenue'),
        ),
        migrations.AddField(
            model_name='seasonmatch',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_won', to='season.team'),
        ),
    ]
